### ISSUE TITLE
Integer type not being recognized, everything being forced to Numeric

### ISSUE THREAD

**Issue by Vaslo** [transferwise/pipelinewise-target-postgres#84]
I am running the spreadsheets-anywhere tap to pull in some CSV data.   I am using the Meltano schema override to ensure that a month number is typed as an integer.  When your target picks it up, it can't seem to recognize it as one of the other int types and insists on it being a numeric, which is just much too big.  Because of this, it creates an extra column with the number as a numeric and leaves my original column as null.  I've tried smallint, integer, and bigint types and despite your code having the ability to recognize a maximum, it refuses to do it.  Any idea why?

![image](https://user-images.githubusercontent.com/7269272/171744672-61dec10e-1eca-432a-a66f-c7c97db66506.png)

This is one of the ways I have set my schema in the tap, for what it's worth:

```
   schema:
      accounts:
        acct_number:
          type: ["null","string"]
      gl_transactions:
        account:
          type: ["null","string"]
        future:
          type: ["null","string"]
        intercompany_segment:
          type: ["null","string"]
        project:
          type: ["null","string"]  
        effective_year:
          type: ["integer"]
        effective_month:
          type: ["integer"]
```
